database:
    engine1:
        user:
            'MMAPV41'
        password:
            'MMAPV411556'
        ip_address:
            '192.168.4.32'
        port:
            '1521'
    engine2:
        user:
            'MMAPV4_PROJECT_CENTRAL'
        password:
            'MMAPV4_PROJECT_CENTRAL1403'
        ip_address:
            '192.168.5.21'
        port:
            '1521'
    table1:
        table_pairs_person_id:
            'temp_pairs_id'
        table_registration:
            'T_KC21'
        table_result:
            'temp_wuxi_result'
    table2:
        table_pairs_person_id:
            'temp_pairs_id'
        table_registration:
            'KC21'
        table_result:
            'temp_wuxi_result'
        table_output:
            'KC_RESULT'
        table_filtered_disease:
            'T_DISEASE'
    columns:
        person_id:
            'person_id'
        medical_id:
            'med_clinic_id'
        person_identification:
            'identity_card'
        person_name:
            'person_nm'
        hospital_id:
            'med_ser_org_no'
        admission_date:
            'in_hosp_date'
        discharge_date:
            'out_hosp_date'
        diagnosis_name:
            'out_diag_dis_nm'
        diagnosis_code:
            'out_diag_dis_cd'
        medical_ cost:
            'med_amount'
        personal_cost:
            'personal_cost'
        clinic_type:
            'clinic_type'

parameter:
    days_interval:
        3
    max_group_number:
        8
    cheat_flag:
        1
    start_date:
      '20180101'
    end_date:
      '20181231'
